### ISSUE TITLE
Link is not copied 

### ISSUE THREAD

**Issue by gourav6m17** [RohtanshSehgal/FlixTorr#1]
When click on copy link! it show popup but link is not copied. please check this issue.

**Comment by RohtanshSehgal** [comment]
Hey @gourav6m17 can you tell me on what browser you used this?

**Comment by gourav6m17** [comment]
> Hey @gourav6m17 can you tell me on what browser you used this?

I'm using Brave and Chrome browser and I checked on both but link is not copied.

**Comment by RohtanshSehgal** [comment]
Ive checked in multiple browsers, it is working but i will find a robust solution for this and update you.
Hey @gourav6m17 you may recheck too.

**Comment by gourav6m17** [comment]
I have checked multiple times it's work upon safari great but on brave and chrome browser link is not copied. Hope this issue will improve app.

**Comment by gourav6m17** [comment]
Hey! @RohtanshSehgal everything is working awesome on every browser after new release. Great Work! Keep it up👍🏻
